version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./boxinator-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    depends_on:
      - backend

networks:
  default:
    driver: bridge
